package com.mhp.requestmicro.entity.table;

public enum DayType {
    OUT_OF_BOUNDS,
    UNINITIALIZED,
    VACATION,
    VACATION_PENDING,
    HOME_OFFICE_WHOLE_DAY,
    HOME_OFFICE_FIRST_HALF,
    HOME_OFFICE_SECOND_HALF,
    HOME_OFFICE_PENDING_WHOLE_DAY,
    HOME_OFFICE_PENDING_FIRST_HALF,
    HOME_OFFICE_PENDING_SECOND_HALF
}
